vim.g['coc_global_extensions'] = {
    '@yaegassy/coc-volar',
  'coc-css',
  'coc-docker',
  'coc-eslint',
  'coc-gitignore',
  'coc-html',
  'coc-jedi',
  'coc-json',
  'coc-marketplace',
  'coc-phpls',
  'coc-sh',
  'coc-stylelint',
  'coc-tsserver',
  'coc-ultisnips',
  'coc-webpack',
  'coc-xml',
  'coc-yaml'
}
